---
name: Run Selenium Test

on: [push, pull_request]

jobs:
  selenium:
    name: Run Selenium Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SetUp Python
        uses: actions/setup-python@v1
        with:
           python-version: 3.8

      - name: SetUp GeckoDriver
        uses: browser-actions/setup-geckodriver@latest

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run!!
        run: python main.py

      - name: Update log
        uses: actions/upload-artifact@v2
        with:
          name: log
          path: *.log
...